development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: station_development
  username: station
  password: passw0rd

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: station_test
  username: station
  password: passw0rd

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: station_production
  username: station
  password: passw0rd
