development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: queue_development
  username: queue
  password: passw0rd

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: queue_test
  username: queue
  password: passw0rd

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: queue_production
  username: queue
  password: passw0rd
